project:
  type: website
  resources:
    - CNAME

website:
  title: "Khang Quach - Data Analyst and Cognitive Scientist"
  site-url: https://khangquach.com
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    
    



